Django-Dependent-Dropdown/ajax/urls.py
from django.urls import path

from ajax.views import home, loadsubcat

urlpatterns = [
    path('',home,name="home"),
    path('load-subcat/',loadsubcat,name="load_subcat")
]

Django-Dependent-Dropdown/ajax_view/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ajax.urls'))
]

Django-Dependent-Dropdown/ajax/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=50)
    
    def __str__(self):
        return self.title
    
class SubCategory(models.Model):
    title = models.CharField(max_length=50)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title
    
class Product(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    subcat = models.ForeignKey(SubCategory,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

Django-Dependent-Dropdown/ajax/forms.py
from django.forms import ModelForm
from .models import Product, SubCategory

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        print(self.fields)
        
        self.fields['subcat'].queryset = SubCategory.objects.none()
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})
        self.fields['title'].widget.attrs.update({'placeholder':'Enter Product Name'})
        
        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                
                self.fields['subcat'].queryset = SubCategory.objects.filter(category_id = category_id).order_by('title')
                
            except(ValueError, TypeError):
                pass
        elif self.instance.id:
            self.fields['subcat'].queryset = self.instance.category.subcat_set.order_by('title')
        

Django-Dependent-Dropdown/ajax/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render

from ajax.forms import ProductForm
from .models import Category, SubCategory

# Create your views here.
def home(request):
    form = ProductForm()
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            print("Invalid Form..")
    
    return render(request,'home.html',{
        'form':form
    })
    
def loadsubcat(request):
    cat_id = request.GET.get('cat_id')
    print(cat_id)
    
    sub_cats = SubCategory.objects.filter(category_id = cat_id)
    print(sub_cats)
    return render(request,'sub_cats.html',{
        'sub_cats':sub_cats
    })
    

Django-Dependent-Dropdown/templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Filter Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top mb-5">
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="#">Bootstrap</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#">React</a>
              </li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container mt-5 p-4">

      <h3>Dependent Dropdown in Django</h3>
      <!--Search Form with csrf token-->

<form method="post" id="personForm" data-cities-url="{% url 'load_subcat' %}">
    {% csrf_token %}

    <div class="row container">
        <div class="col-4">
          {{form.category.label}}
          <hr>
          {{form.category}}
        </div>
        <div class="col-lg-4">
          {{form.subcat.label}}
          <hr>
          {{form.subcat}}
        </div>
        <div class="col-lg-4">
          {{form.title.label}}
          {{form.title}}
        </div>
    </div>

    <input type="submit" value="Submit" class="btn btn-primary mt-2">
</form><!--Display Output -->


    </main>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<script>
    $('#id_subcat').hide()

    $('#id_category').change(function(){
      const url = '/load-subcat/'
      cat_id = $(this).val();
      console.log(cat_id)
      
      $.ajax({
        url : url,
        data:{
          'cat_id':cat_id
        },
        success : function(data){
          $('#id_subcat').html(data)
          $('#id_subcat').show()
        }
      })
    })
</script>

</body>

</html>

Django-Dependent-Dropdown/templates/sub_cats.html
<option value="">---------</option>
{% for sub_cat in sub_cats %}
<option value="{{ sub_cat.id }}">{{ sub_cat.title }}</option>
{% endfor %}